### ISSUE TITLE
iDisplayLength to length

### ISSUE THREAD

**Issue by toben** [mcintyre321/mvc.jquery.datatables#105]
Maybe I am wrong but i am using the last version of datatables. But the class DataTablesParam has a "iDisplayLength" and a "iDisplayStart" instead of "length" and "start" sent by the datatables. How can i solve this ?

**Comment by mcintyre321** [comment]
What problem are you having? I think the latest datatables is backwards compatible

**Comment by toben** [comment]
I don't know but when I am using datatables, it sends only : start = 0 and length = 10 in the http request.

**Comment by mcintyre321** [comment]
What version of datatables have you got referenced in the client side?

**Comment by mcintyre321** [comment]
Please compare your project to the example project from this repo.

**Comment by gjstockham** [comment]
Just hit this myself.  The 1.10 version uses different ajax parameters.  You can use the old parameter names by setting 

$.fn.dataTable.ext.legacy.ajax = true;

**Comment by mcintyre321** [comment]
I can't reproduce this in my repo, even if I update the datatables version to 1.10.5 - what version are you using?

**Comment by gjstockham** [comment]
1.10.5 - the one from the CDN.

I get the parameters as detailed here: http://www.datatables.net/manual/server-side unless I use the legacy flag.

**Comment by gjstockham** [comment]
I've forked the code - will see if I can see the issue.

**Comment by gjstockham** [comment]
https://datatables.net/upgrade/1.10-convert

I'm guessing that the way it's being initialized is somehow forcing the old parameters?

**Comment by mcintyre321** [comment]
Ah that rings a bell - I think there is an old way and a new way. What's
interesting is that you guys ran into it. Do you have your own modified
version of DataTable.cshtml?

**Comment by gjstockham** [comment]
No, I started from plain version as on the DT website doing client-side processing, then set up server side processing.  I then tried to implement the backend using your nuget package.  I've had to take a different approach now (nothing to do with this issue) but  I'll probably be revisiting this problem soon.

**Comment by mcintyre321** [comment]
https://github.com/mcintyre321/mvc.jquery.datatables/issues/115
