### ISSUE TITLE
Action Column

### ISSUE THREAD

**Issue by JakubHolovsky** [mcintyre321/mvc.jquery.datatables#106]
Hello, this is more of a question rather than an issue but I might as well ask here.

I have been trying out your nugget package and I like it a lot. The thing is that in our table we need to display links, buttons in an extra action column.

Let's say that in our table we would be displaying user that has following properties:
FirstName,
LastName,
Age

Then we need to add one more column that would read as following:
Actions

and would links/buttons that would point to user profile, editing user profile page etc.

Could you tell me what would be the cleanest approach to add an action column if I was using your library.

**Comment by mcintyre321** [comment]
This page should explain:

https://github.com/mcintyre321/mvc.jquery.datatables/wiki/How-to-manipulate-format-prettify-the-output-column-data-after-the-filters-have-been-applied

**Comment by mcintyre321** [comment]
Create an extra empty string property on your row view model type for actions, and put the html in the transform of  DataTablesResult.Create (similar to how the User row is decorated in the example)

**Comment by JakubHolovsky** [comment]
Thanks, that seems like exactly what I was after!
