### ISSUE TITLE
edit and delete  rows

### ISSUE THREAD

**Issue by addisroberto** [mcintyre321/mvc.jquery.datatables#107]
hello I apologize for my English
I installed it on my project MVC library Mvc.JQuery.Datatables and after some modifications on the project, I was able to run the datatable
everything is perfect and you do the achievements for the work done.
I have only one question in the datatable, I do not find the way to bring back the edit button for each row and delete row.
could you give me some information about.
thank you.

**Comment by mcintyre321** [comment]
see https://github.com/mcintyre321/mvc.jquery.datatables/issues/106

**Comment by addisroberto** [comment]
ok solved in this way
if it can be of help

        //public DataTablesResult<movimenti> Getmovimenti(DataTablesParam dataTableParam)
        //{
        //    var movimenti = db.movimenti.Include(m => m.prodotti);
        //    return DataTablesResult.Create(movimenti, dataTableParam, x => new
        //    {
        //        id = string.Format("<a href='./movimentiedit/{0}'>Modifica</a>", x.id),
        //        idprodotto = "<b>" + x.prodotti.nomeprodotto + "</b>"
        //    });
        //}
