### ISSUE TITLE
Apply CSS on row level

### ISSUE THREAD

**Issue by JakubHolovsky** [mcintyre321/mvc.jquery.datatables#108]
Hello, is there a way to apply CSS class on a row level using your plugin?

**Comment by mcintyre321** [comment]
I think you can do it using fnDrawCall back or fnCreatedRow 

See https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables.Example/Views/Home/_ExampleTable.cshtml#L27

*I haven't testedf this with v1.10+ of datatables, maybe the callbacks have changed
