### ISSUE TITLE
DataTableConfigVm.Dom incompatible with Bootstrap

### ISSUE THREAD

**Issue by 42Johannes** [mcintyre321/mvc.jquery.datatables#109]
I use DataTables.net in combination with Bootstrap. If I use the script dataTables.bootstrap.js the default sDom option is "<'row'<'col-xs-6'l><'col-xs-6'f>r>t<'row'<'col-xs-6'i><'col-xs-6'p>>" which uses the css layouting provided by bootstrap.

But DataTableConfigVm.Dom has only a getter which provides only a "classic" sDom string but no support for the Bootstrap styles.

    public string Dom
    {
      get
      {
        string str = "";
        if (this.ColVis)
          str += "C";
        if (this.TableTools)
          str += "T<\"clear\">";
        if (this.ShowPageSizes)
          str += "l";
        if (this.ShowSearch)
          str += "f";
        return str + "tipr";
      }
    }

Please add support for Bootstrap or change the Dom property to allow it to be overwritten so I can write my own DOM positioning string. Example:

    private string _dom;

    public string Dom
    {
        get
        {
            if (!string.IsNullOrEmpty(_dom))
                return _dom;

            string str = "";
            if (this.ColVis)
                str += "C";
            if (this.TableTools)
                str += "T<\"clear\">";
            if (this.ShowPageSizes)
                str += "l";
            if (this.ShowSearch)
                str += "f";
            return str + "tipr";
        }

        set { _dom = value; }
    }

**Comment by mcintyre321** [comment]
Hi, I'm more than happy to accept a a pull request for this.

**Comment by mcintyre321** [comment]
Closing due to lack of followup.
