### ISSUE TITLE
Changing bLengthChange

### ISSUE THREAD

**Issue by shaahink** [mcintyre321/mvc.jquery.datatables#110]
jQuery Datatables has a feature that let the user select the size of the formatted page.
In the Datatables we can turn this off by setting bLengthChange to false.
Without using jQuery / css tricks (like hiding the dropwdown) is there any way to set this property when using mvc.jquery.datatables ?

Thanks

**Comment by mcintyre321** [comment]
If you send me a pull request with bLengthChange I will merge it in. It should default to true so that existing behaviour isn't changed.

**Comment by mcintyre321** [comment]
Closed to due lack of PR
