### ISSUE TITLE
Suggestion to use TypeDescriptor 

### ISSUE THREAD

**Issue by ramyhhh** [mcintyre321/mvc.jquery.datatables#112]
Hello ... I suggest using TypeDescriptor  class to read DataTables attributes instead of using normal reflection because TypeDescriptor  gives the advantage of reading dynamically injected attributes.
Why would dynamically injected DataTables be useful? I had a case where I want to use the models classes directly (no need to transform them into view classes) but those classes where already built inside a dll lib so I couldn't specify the DataTables attributes.
By using TypeDesciptor I could've inject the required attributes instead of writing new classes and transformation methods.

**Comment by mcintyre321** [comment]
It sounds like it might be a lot of work for an edge case, and I don't know enough about using TypeDescriptor to know the pros/cons. Could you show me an example of the code change?

**Comment by ramyhhh** [comment]
It does not require a lot of work ... I rewrote the code in the DataTablesInfo.cs file as follows:

internal static class DataTablesTypeInfo
    {
        internal static DataTablesPropertyInfo[] Properties(Type type)
        {

            var typeDescriptor = TypeDescriptor.GetProvider(type).GetTypeDescriptor(type);
            if (typeDescriptor == null) return new DataTablesPropertyInfo[0];

            var infos = (from PropertyDescriptor pi in typeDescriptor.GetProperties()
                         let attributes = pi.Attributes.Cast<Attribute>().OfType<DataTablesAttributeBase>().ToArray()
                         orderby attributes.OfType<DataTablesAttribute>().Select(a => a.Order as int?).SingleOrDefault() ?? int.MaxValue
                         select new DataTablesPropertyInfo(pi, attributes)).ToArray();

            return infos;
        }
    }
    static class DataTablesTypeInfo<T>
    {
        internal static DataTablesPropertyInfo[] Properties { get { return DataTablesTypeInfo.Properties(typeof(T)); } }


        public static Dictionary<string, object> ToDictionary(T row)
        {
            var dictionary = new Dictionary<string, object>();
            foreach (var pi in Properties)
            {
                dictionary[pi.PropertyInfo.Name] = pi.PropertyInfo.GetValue(row);
            }
            return dictionary;
        }

        public static OrderedDictionary ToOrderedDictionary(T row)
        {
            var dictionary = new OrderedDictionary();
            foreach (var pi in Properties)
            {
                dictionary[pi.PropertyInfo.Name] = pi.PropertyInfo.GetValue(row);
            }
            return dictionary;
        }


    }


Changes are:
- No need to cache properties loaded for types (since TypeDescriptor internally cache them
- Replace PropertyInfo class with PropertyDescriptor (with some refactoring)


I have done those changes and it's working just fine :)

Thank you very much

**Comment by mcintyre321** [comment]
If you submit a PR I'll give it a go.

**Comment by mcintyre321** [comment]
Closing due to tumbleweed
