### ISSUE TITLE
DataTablesParam being null

### ISSUE THREAD

**Issue by pau7** [mcintyre321/mvc.jquery.datatables#113]
Hi, im using your dll in my project, but i keep getting null on datatableparam,
this is the options of my controller:
<code>$scope.options = {
        bServerSide: true,
        'ajax':
        {
            'url': 'Api/CategoryApi/getAll',
            'dataSrc': ""
        },
        aoColumns: [{
            "sTitle": "Id"
        }, {
            "sTitle": "Surname"
        }, {
            "sTitle": "First Name"
        }],
        aoColumnDefs: [{
            "bSortable": true,
            "aTargets": [0, 1, 2]
        }],
        bJQueryUI: true,
        bDestroy: true
    };</code>

And my api controller have this method:
<code>public DataTablesResult<Category> GetAll(DataTablesParam dataTableParam)
        {
            var query = new Sql().Select("*").From("categories");
            return DataTablesResult.Create(DatabaseContext.Database.Query<Category>(query).AsQueryable(), dataTableParam);
        }</code>

I installed with nuget your project, but im not getting value in dataTableParam, can you help me?

**Comment by mcintyre321** [comment]
Is the Model Binder registered? It should have happened automatically when you installed the project.

See:

https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables.Example/RegisterDatatablesModelBinder.cs

**Comment by pau7** [comment]
Yes it is registered

**Comment by mcintyre321** [comment]
If you use fiddler, or Chrome dev tools, can you see  POST requests being
made correctly?

**Comment by pau7** [comment]
Request URL:http://localhost:65055/umbraco/Api/CategoryApi/getAll
Request Method:POST
Status Code:405 Method Not Allowed

I think I was doing a get request by default, i included type post, and i get this error

**Comment by pau7** [comment]
I made post method to work, but now, it says:
Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by pau7** [comment]
Thanks for the help, your dll is working now.
