### ISSUE TITLE
Filtering and searching

### ISSUE THREAD

**Issue by pau7** [mcintyre321/mvc.jquery.datatables#114]
Hi, i'm having a problem with filtering or seaching, it seems that the datatableparams i'm sending to the controller are empty, and the controller always sent back all the data, do you know why this is happenning?

**Comment by mcintyre321** [comment]
Is the DataTablesParam in the controller empty or is it null?

Is the ModelBinder registered?

Does the post request contain the correct data? (Examine using Fiddler)

**Comment by pau7** [comment]
This is the params:
http://i.imgur.com/Vjaj15n.png

The modelBinder is registered

And the post request contains this:
draw	1
columns	[object Object]
columns	[object Object]
columns	[object Object]
order	[object Object]
start	0
length	10
search	[object Object]

but it returns:
sEcho=0
iTotalDisplayRecords=11
iTotalRecords=11
aaData...

I never used Fiddler, but i just intalled it, tell me if you wanna see something from it

**Comment by mcintyre321** [comment]
Please can you post the contents of the POST request, from the 'Raw' tab.

**Comment by pau7** [comment]
POST http://localhost:65055/umbraco/Api/CategoryApi/getAll HTTP/1.1
Host: localhost:65055
Connection: keep-alive
Content-Length: 161
Pragma: no-cache
Cache-Control: no-cache
Origin: http://localhost:65055
X-XSRF-TOKEN: yv6m2K3m71fmJXYPJn__rP92R_EaeILKzuFN3CiFUObrhrWO9PTHrVSs40dIeieuJ0PC-biDKfTyu_4-Ygw1tYWYpyBa76T1tMrTmb7wLkSKtPbihaKMqKavbIEovfdt0
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Referer: http://localhost:65055/umbraco/
Accept-Encoding: gzip, deflate
Accept-Language: es,ca;q=0.8
Cookie: XSRF-TOKEN=yv6m2K3m71fmJXYPJn__rP92R_EaeILKzuFN3CiFUObrhrWO9PTHrVSs40dIeieuJ0PC-biDKfTyu_4-Ygw1tYWYpyBa76T1tMrTmb7wLkSKtPbihaKMqKavbIEovfdt0; XSRF-V=_NWfuHGGUSI7dtHFrv4LQuFlrQjCAYP5mfWvlzi-lmrB8O7HLXRhVUxylIih1tqOssgU3HC6oKHfGKk3Gb8LWhFXjGAXStWZyNXFs8Y22KU1; UMB_UPDCHK=1; UMB_UCONTEXT=11666FFCAFC4E7B31E445DA40E85EF8BCB99A80EDE95CD44BF6E3EF2076162D81E2CB82C4F765E2BFD68D4113EBD942E583DA6958A3134275F8D9C6EDAEA0E03B5B1311E4DF2F46967612639176BA3E339D89018C6A4911F8DA800FC2F0ED8BDFA2AE44D8DCDFA0130FDBAC23551046E4DF18D9287CE552A1920E385080C98D50D82E8A3B5B9D7FC5183AE943106A41CDC7D686C52CBCE838773F97C0D3D119B988EE5C30306E97D88C66DE2EF3E073A23467DB9ABCE27CD88E5938143706CFF07561EF6365DDBCC67834843985788980699377F87C8CBC44FD25237466C56C001310728BA5C6793AEA5D6803B952B697310B30888AD1DA994364A7169FF9A0913D9B0A0360E0A36D619080F1FDF4B990FAB074F3685402429ADC8DC335423944A4AD8A050D317576DACF8ADAE0810284448C51069FDBA1086510355AE9276908CEEE75AD604744A0F95B6693C2DF1E77E82AF60E3492ADABFC0D656B59F7626AC0D6F41F4C7C4F9321A5489F8FA8E92AE1B3F7E5671F8FCE9EE8C6379A9133AB8043FC8A41E4AD2A7943C03F72AAABA6D5EE15120BBB7FA35A07C7BA966DA965A1B02F01A6229AA3EAE7C592B599CCD318B18A04E87CC38CB8F1FF028195400EBBE72692F9EED59ED47910175BFDC96E710D93DC121220F4F3E18ADAA82D68FBB6F06DCDB60328D5853FE194F9ADD1478FAA4AAB0109DB6EAB0C48C624BAC735FBD854FEA4849B324E725892CA21ABD

draw=1&columns=%5Bobject+Object%5D&columns=%5Bobject+Object%5D&columns=%5Bobject+Object%5D&order=%5Bobject+Object%5D&start=0&length=10&search=%5Bobject+Object%5D

**Comment by mcintyre321** [comment]
It looks like something has gone wrong with your client side initialization. If you compare this to the [example site] (), the body should contain something like:
```
sEcho=1&iColumns=9&sColumns=%2C%2C%2C%2C%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=false&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=Tester&bRegex_6=false&bSearchable_6=true&bSortable_6=true&mDataProp_7=7&sSearch_7=01%2F01%2F2014+00%3A00~19%2F05%2F2015+00%3A00&bRegex_7=false&bSearchable_7=true&bSortable_7=true&mDataProp_8=8&sSearch_8=&bRegex_8=false&bSearchable_8=true&bSortable_8=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1
```

Are you using the helper to initialize the table?

```
@Html.Partial("DataTable", Html.DataTableVm("table-id", (HomeController h) => h.GetUsers(null)))
```

**Comment by pau7** [comment]
No, i create the datatable on a directive from angular:

app.directive('myTable', function () {
    return {
        restrict: 'E, A, C',
        link: function (scope, element, attrs, controller) {
            var dataTable = element.dataTable(scope.options);

            scope.$watch('options.aaData', handleModelUpdates, true);

            function handleModelUpdates(newData) {
                var data = newData || null;
                if (data) {
                    dataTable.fnClearTable();
                    dataTable.fnAddData(data);
                }
            }
        },
    };
});

**Comment by mcintyre321** [comment]
Ah, might have been handy to say so earlier!

I haven't integrated it with angular before, so you'll need to base the
initialisation code off the source on the example page, and figure it out
from there.

http://aspdatatables.azurewebsites.net/

**Comment by pau7** [comment]
I gonna try this:
http://i.imgur.com/fXiIqli.png

With the JObject getting the params, i'll create your DatatableParam object and continue with your DatatableResult.create, i think it should work

**Comment by pau7** [comment]
Can you help me to convert that JObject into your DatatableParams i think, its something like this, but i'm not sure on some parameters

public int iDisplayStart { get; set; }                                       // start
public int iDisplayLength { get; set; }                                     // length
public int iColumns { get; set; }                                            // columns.length
public string sSearch { get; set; }                                         // search.value
public bool bEscapeRegex { get; set; }                               // search.regex
public int iSortingCols { get; set; }                                       // order.column
public int sEcho { get; set; }                                               // draw
public List<bool> bSortable { get; set; }                             // for each colum orderable
public List<bool> bSearchable { get; set; }                        // for each colum searchable
public List<string> sSearchColumns { get; set; }              // for each colum search.value
public List<int> iSortCol { get; set; }                                  // not sure
public List<string> sSortDir { get; set; }                            // not sure
public List<bool> bEscapeRegexColumns { get; set; }     // for each colum search.bool

**Comment by mcintyre321** [comment]
The code is here.

You can find help here: http://legacy.datatables.net/ref but I think the
problem is that you are using the new initialisation syntax - this library
still uses the old (legacy) approach.

http://www.datatables.net/upgrade/1.10

Try:

$(...).dataTable()

instead of

$(...).DataTable()

**Comment by mcintyre321** [comment]
https://github.com/mcintyre321/mvc.jquery.datatables/issues/115

**Comment by pau7** [comment]
I have it working now, i give the method i created.
This is the method GetAll of the ApiController

<code>[System.Web.Http.HttpPost]
        public DataTablesData GetAll([FromBody] JObject param)
        {
            var help = new ParamHelper();
            var res = help.convert(param);
            var query = new Sql().Select("*").From("categories");
            var result = DataTablesResult.Create(DatabaseContext.Database.Query<Category>(query).AsQueryable(), res);
            return result.Data;
        }</code>

This is the helper method i create to convert the JObject params in your DatatableParams:

<code>
public DataTablesParam convert(JObject param)
        {
            JToken token = param;
            var cols = token.SelectToken("columns");
            var orders = token.SelectToken("order");
            int numCols=0;
            int numOrders = 0;
            var result = new DataTablesParam();            
            foreach (var i in cols.ToList()){
                var serch = i.SelectToken("search");
                result.bSortable.Add(Convert.ToBoolean(i.SelectToken("orderable")));
                result.bSearchable.Add(Convert.ToBoolean(i.SelectToken("searchable")));
                result.sSearchColumns.Add(Convert.ToString(serch.SelectToken("value")));
                result.bEscapeRegexColumns.Add(Convert.ToBoolean(serch.SelectToken("regex")));
                numCols++;
            }
            foreach (var i in orders.ToList())
            {
                result.iSortCol.Add(Convert.ToInt32(i.SelectToken("column")));
                result.sSortDir.Add(Convert.ToString(i.SelectToken("dir")));
                numOrders++;
            }
            var search = token.SelectToken("search");
            ;
            result.iDisplayStart = (int)token.SelectToken("start");
            result.iDisplayLength = (int)token.SelectToken("length");
            result.iColumns = numCols;
            result.sSearch = (string)search.SelectToken("value");
            result.bEscapeRegex = (bool)search.SelectToken("regex");
            result.iSortingCols = numOrders;
            result.sEcho = (int)token.SelectToken("draw");
            
            
            return result;
        }
</code>

It's a bit shitty to see here, thanks for the help.
