### ISSUE TITLE
Suggestion to return array of objects instead of 2-dimensional array

### ISSUE THREAD

**Issue by offspringer** [mcintyre321/mvc.jquery.datatables#117]
Since the latest versions of Datatables support the use of object array, I suggest the modification of the class DataTableResult to support it. By removing this last transformation call on the Create method, I was able to accomplish this task: 

Transform&lt;Dictionary&lt;string, object&gt;, object[]&gt;(d =&gt; { return d.Values.ToArray(); })

This last transformation is completely ignoring the keys. I know there's an overhead by supplying the key name instead of its index, but at least having the option to choose among them would be nice.

Btw, I'm using it in a scenario where I let Handlebars.js render some portions of the table, and having the property names makes this task much easier. And I'm also not using the provided helpers to render the javascript. I think it would be more future proof (regarding datatable.js updates) and easier to maintain it those classes were in a separated project, leaving its core more lightweight.

And congratulations for the good work!

**Comment by mcintyre321** [comment]
Could you subclass DataTable result and create an overload for your requirement, leaving the old api in place for other users?

I'd like to keep option builders as a core feature - I use them to dynamically build grids with different option depending on user settings, and I don't think having a few classes for outputting json would cause problems for people. 

I want to remove the dependency on MVC though, and have that in another assembly. This is a big job though, as DataTablesResult etc. are all dependent on the framework. Also not having static create methods and rule registrys would be nice. Oh for a week to spend refactoring!
