### ISSUE TITLE
Paging not working on nhibernate

### ISSUE THREAD

**Issue by beratcarsi** [mcintyre321/mvc.jquery.datatables#124]
Hi, 
I need help.
I use nhibernate my project. 

**this is working.**
>var articleGridModels = Context.ArticleList().Select(x => new ArticleGridModel() { Id = x.Id, Title = x.Title });
>return DataTablesResult.Create(articleGridModels, dataTableParam);

**this  is not working**
>dataTableParam.iDisplayStart = 5; // probably conflicts nhibernate query.. i don't know.
>var articleGridModels = Context.ArticleList().Select(x => new ArticleGridModel() { Id = x.Id, Title = x.Title });
            return DataTablesResult.Create(articleGridModels, dataTableParam);

**exception :**
[ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index]
   System.ThrowHelper.ThrowArgumentOutOfRangeException() +72
   System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index) +18
   NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery) +142
   NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression) +50
   NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression) +11
   System.Linq.Queryable.Count(IQueryable`1 source) +233
   Mvc.JQuery.Datatables.DataTablesResult`1.GetResults(IQueryable`1 data, DataTablesParam param) +491
   Mvc.JQuery.Datatables.DataTablesResult.Create(IQueryable`1 q, DataTablesParam dataTableParam, Func`2 transform) +110
   Cms.Management.Controllers.ArticleController.GetList(DataTablesParam dataTableParam) in c:\Repository\Berat.Cms\Applications\Management\Cms.Management\Controllers\ArticleController.cs:51
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +182
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41() +28
   System.Web.Mvc.Async.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33() +58
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +225
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +24
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +99
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +14
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +25
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9629708
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

-

probably conflicts nhibernate query.. i don't know.

please help me. thanks.

**Comment by mcintyre321** [comment]
Why are you setting the iDisplayStart value manually? It will be set by posted request.

**Comment by beratcarsi** [comment]
Yes. I know. to show error reason. i know a little english. i am sorry (:

**Comment by mcintyre321** [comment]
Does your IQueryable work with skip and take? i.e. does this work
```
var articleGridModels = Context.ArticleList().Select(x => new ArticleGridModel() { Id = x.Id, Title = x.Title }).Skip(5);
return DataTablesResult.Create(articleGridModels, dataTableParam);
```

**Comment by beratcarsi** [comment]
yes nhibernate IQueryable work with skip and take.
DataTablesResult.Create method the same throw exception.

**Comment by beratcarsi** [comment]
simple test scenario repo : https://github.com/beratcarsi/Fluent-NHibernate-MVC-3

**Comment by beratcarsi** [comment]
no answer?

**Comment by mcintyre321** [comment]
I don't actually have SQL installed at the moment, so I can't try out your code. If you can submit a version with 

The problem must lie with the NHibernates LINQ providers ability to handle the Expression generated by DataTables - you can see from the stack trace that there is a problem within NHibernate.

```
[ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index]
System.ThrowHelper.ThrowArgumentOutOfRangeException() +72
System.Collections.Generic.List1.System.Collections.IList.get_Item(Int32 index) +18 NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery) +142 NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression) +50 NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression) +11 System.Linq.Queryable.Count(IQueryable1 source) +233
```

The Expressions generated by DataTables work with Linq To Objects and Entity Framework, so I'm pretty confident the issue will be with NHibernate. I'll download SQL when I get a chance in order to confirm.

**Comment by mcintyre321** [comment]
The bug is in NHibernate - if you run this query before doing any Datatables stuff:

`var pageCount = articleGridModels.Skip(5).Take(5).Count();`

It will throw 
```
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  ParamName=index
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
       at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
       at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
       at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
       at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
       at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
       at FluentNHibernateMvc3.Controllers.HomeController.GetList(DataTablesParam dataTableParam) in C:\Users\Harry\Downloads\Fluent-NHibernate-MVC-3-master\Fluent-NHibernate-MVC-3-master\FluentNHibernateMvc3\Controllers\HomeController.cs:line 37
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
  InnerException: 
```

**Comment by mcintyre321** [comment]
There is another person running into this here http://permalink.gmane.org/gmane.comp.windows.dotnet.nhibernate.user.general/20637

**Comment by beratcarsi** [comment]
Thank you.
