### ISSUE TITLE
FYI the demo is broken

### ISSUE THREAD

**Issue by papyr** [mcintyre321/mvc.jquery.datatables#128]
Love the work... just curious how you come up with these ideas... and what tools do you play with to debug or try out the JS code with MVC

Server Error in '/' Application.

Compilation Error

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS1061: 'System.Web.Mvc.HtmlHelper<dynamic>' does not contain a definition for 'DataTableVm' and no extension method 'DataTableVm' accepting a first argument of type 'System.Web.Mvc.HtmlHelper<dynamic>' could be found (are you missing a using directive or an assembly reference?)

Source Error:

Line 21: 
Line 22: @{
Line 23:     var vm = Html.DataTableVm("table-id", (HomeController h) => h.GetUsers(null));
Line 24:     //vm.JsOptions.Add("iDisplayLength", 25);
Line 25:     //vm.JsOptions.Add("aLengthMenu", new object[] { new[] {5, 10, 25, 250, -1} , new object[] { 5, 10, 25, 250, "All"} });

Source File: d:\home\site\wwwroot\Views\Home\_ExampleTable.cshtml    Line: 23 

Show Detailed Compiler Output:

Show Complete Compilation Source:

**Comment by mcintyre321** [comment]
Thanks, fixed.
