### ISSUE TITLE
After upgrading to NuGet package 1.3.18. from 1.2.155, DataTablesResult disappeared

### ISSUE THREAD

**Issue by MrCsabaToth** [mcintyre321/mvc.jquery.datatables#129]
The C# backend code doesn't compile any more.
Old packages.config:
```  <package id="Mvc.JQuery.Datatables" version="1.2.155" targetFramework="net45" />
  <package id="Mvc.JQuery.Datatables.Templates" version="1.2.155" targetFramework="net45" />```
New:
```  <package id="Mvc.JQuery.Datatables" version="1.3.18" targetFramework="net45" />
  <package id="Mvc.JQuery.Datatables.Core" version="1.3.14" targetFramework="net45" />
  <package id="Mvc.JQuery.Datatables.Templates" version="1.3.18" targetFramework="net45" />```

**Comment by MrCsabaToth** [comment]
Example code which doesn't compile:
```return DataTablesResult.Create(calculationChecks.AsQueryable(), dataTableParam);```

**Comment by mcintyre321** [comment]
Can you try again with 1.3.20 - there were some duff builds which got partially pushed up. The example project works now, so that code should work too. Reopen if you have further difficulties.

**Comment by MrCsabaToth** [comment]
I upgraded to 1.3.22 but the DataTablesResult class is still gone. Maybe I'm following a wrong patter?

**Comment by MrCsabaToth** [comment]
Oh, now it's in Mvc.JQuery.DataTables instead of Mvc.JQuery.Datatables;

**Comment by mcintyre321** [comment]
Yep, sorry, the mismatch in capitalization caused all sorts of mayhem,
