### ISSUE TITLE
Create Symbol package

### ISSUE THREAD

**Issue by martimarkov** [mcintyre321/mvc.jquery.datatables#131]
Would it be possible to create a Symbol Package? https://docs.nuget.org/create/creating-and-publishing-a-symbol-package

I'm having an index out of range problem and I can't debug it properly.

**Comment by mcintyre321** [comment]
I've just pushed a new version.

You aren't using NHibernate by any chance are you?

**Comment by martimarkov** [comment]
I'm using Unity.

**Comment by mcintyre321** [comment]
Ah OK. Another user had IndexOutOfRange when using NHibernate, thats all.

**Comment by martimarkov** [comment]
Yeah, I saw that issue but its a different error as far as I can see.
