### ISSUE TITLE
Out-of-date dlls from NuGet

### ISSUE THREAD

**Issue by davepye** [mcintyre321/mvc.jquery.datatables#134]
When installing the mvc.jquery.datatables library using the package manager console within Visual Studio the namespacing within the project dlls were different to what was expected.

I had developed my application using the source code from GitHub (latest commit Oct 2, 2015). However once I had removed the source code and used the package manager console to install the package the dll version were different in mvc.jquery.datatables.core. The name spacing was Mvc.JQuery.Datatables instead of Mvc.JQuery.DataTables and this is definitely wrong.

When I manually downloaded the assemblies from NuGet the namespacing at least was correct. But as the dlls are not properly versioned with correct version numbers there was no way of understanding exactly what version I had got.

However installing with the package mananger console definetely provides the wrong dlls. 

I think this should be looked into.

**Comment by mcintyre321** [comment]
So the js lib capitalise the T, so I'd like to standardise on that.

**Comment by mcintyre321** [comment]
Updated, please grab the latest
