### ISSUE TITLE
NuGet package dependency broken

### ISSUE THREAD

**Issue by bak-t** [mcintyre321/mvc.jquery.datatables#136]
The latest Mvc.JQuery.DataTables package (1.3.28) has dependency on exactly 1.0.0.0 version of Mvc.JQuery.DataTables.Core which isn't available on NuGet.

It seems that `$version$` token used for substitution in _/Mvc.JQuery.Datatables/Mvc.JQuery.Datatables.nuspec_ has different values in `metadata` section & `dependencies` subsection.

**Comment by mcintyre321** [comment]
New version pushed, this should be fixed. 

It seems Nuget pack chooses to pull $version$ from the AssemblyVersion, not the -version parameter. I've patched the AssemblyVersion to match the build number.
