### ISSUE TITLE
Missing bootstrap-overrides.css file in Example project

### ISSUE THREAD

**Issue by tcs021** [mcintyre321/mvc.jquery.datatables#137]
In the Example project, the _Layout.cshtml tries to link to "~/Content/bootstrap-overrides.css" which does not exist in the repo.  Is this a file that exists that did not get committed, or should the link be removed?

I was thinking that the file may exist and was just not committed, since the styling on the demo site does not match the style shown in the screencapture that is part of the readme.

If the link just needs to be removed, I will do that and submit as part of planned PR.

**Comment by mcintyre321** [comment]
The styling in the example project is a little off - the close buttons for
the filter popups display weirdly.

There's nothing deliberate going on and any improvements to the example
project are more than welcome

**Comment by MrCsabaToth** [comment]
But I find no traces of the bootstrap-overrides.css in the source. The source of http://aspdatatables.azurewebsites.net/ supposed to be somewhere in https://github.com/mcintyre321/mvc.jquery.datatables/tree/master/Mvc.JQuery.Datatables.Example ?

**Comment by MrCsabaToth** [comment]
I've found multiple bootstraps in the demo, https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables.Example/Content/bootstrap.css is 1.4 (!!!), https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables.Example/Scripts/bootstrap.js is 2.0.1 ...

**Comment by mcintyre321** [comment]
I think the link to bootstrap-overrides.css is there erroneously and can be removed. The whole project could be updated to a more recent version of bootstrap by someone with the time - please do so if you have the will!

**Comment by danmiser** [comment]
It looks like you may have solved this with your May 10th commit

**Comment by mcintyre321** [comment]
Ah awesome, I'll close this one, thanks.
