### ISSUE TITLE
there is no DataTablesFilterType to remove filter for a column

### ISSUE THREAD

**Issue by peppo1616** [mcintyre321/mvc.jquery.datatables#139]
How to disable a filter in column?
I've not found a way from examples

**Comment by mcintyre321** [comment]
Put a [DataTables(Searchable=false)] atttribute on

**Comment by peppo1616** [comment]
seems not to work, it disable search but the filter is drawn as the same way, i want to hide it completely.

**Comment by mcintyre321** [comment]
I've just added the ability to configure this via an attribute: `[DataTablesFilter(DataTablesFilterType.None)]`

Or you can used the fluent config in the view: 
`    vm.FilterOn("SomeColumn").None()`
