### ISSUE TITLE
Filter on Relationship

### ISSUE THREAD

**Issue by Glennvd** [mcintyre321/mvc.jquery.datatables#140]
Is there any way to easily filter on a relationship? So on a Guid/Id but with descriptions as display values? I'm trying with the dropdown filterOn but I can't find much documentation.

**Comment by mcintyre321** [comment]
So to choose from a list of predefined key-value pairs?

**Comment by Glennvd** [comment]
Essentially, but this should be supported in the search as well as creating the filter. I don't know if this is possible with the current implementation? Or being able to pass my own custom argument to the controller function would be sufficient as well.

**Comment by mcintyre321** [comment]
I'm not very clear still - can you give an example of the data, and what kind of ui element you want in the filter header?
