### ISSUE TITLE
Links to show example are broken on 

### ISSUE THREAD

**Issue by ademgashi** [mcintyre321/mvc.jquery.datatables#141]
Hi @mcintyre321 I hope this message finds you well with everything. I love your project and I hope to see all the features of the datatables implemented on it.

Just wanted to note that Create a controller (see example) and render the partial (see example) link on the demo site are not working.

I know this might not be the place to post this issue but it was the only way to notify you.

Best Regards
Keep the good code coming :)

**Comment by mcintyre321** [comment]
Thanks, there are quite a few issues on the docs. I'll take a look at them when I get a chance (or any pull requests gratefully accepted!)
