### ISSUE TITLE
Filtering offset issue with column filter and Visible = false attribute

### ISSUE THREAD

**Issue by peppo1616** [mcintyre321/mvc.jquery.datatables#146]
Hi i've found some kind of bug, i've got a class with property like that.

Note that there are some visible=False and Searchable=False columns between visible column. If i load in my view the ColumnFilter option set to true, when i'm filtering for "Title" (Property not after a visible=false property) all it's ok, but when i'm filtering for "Creator" (that's after a visible=False property), in server side filter is appening on "Rights" Property!

        [DataTables(DisplayName = "Titolo")]
        public virtual string Title { get; set; }

        [DataTables(DisplayName = "Tipologia")]
        public virtual string Type { get; set; }

        [DataTables(Visible = false,Searchable = false)]
        [DataTablesFilter(DataTablesFilterType.None)]
        public virtual string Url { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string CCE { get; set; }

        [DataTables(Visible = false, Searchable = false]
        public virtual string Subject { get; set; }

        [DataTables(DisplayName = "Autore")]
        public virtual string Creator { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Contributor { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Description { get; set; }

        [DataTables(Visible = true)]
        public virtual string Publisher { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Date { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Format { get; set; }

        [DataTables(DisplayName = "Source")]
        public virtual string Source { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Language { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Relation { get; set; }

        [DataTables(Visible = false, Searchable = false)]
        public virtual string Coverage { get; set; }

        [DataTables(DisplayName = "Licenza")]
        public virtual string Rights { get; set; }

My view

        var vm = Html.DataTableVm("table-id", (MediaManageController h) => h.LoadMedia(null));
        vm.StateSave = false;
        vm.ColumnFilter = true;
        vm.TableTools = false;
        @Html.Partial("DataTable",vm );

**Comment by mcintyre321** [comment]
Have you included the colvis plugin?

`

<link rel="stylesheet" href="//cdn.datatables.net/colvis/1.1.1/css/dataTables.colVis.css" />
<script type="text/javascript" src="//cdn.datatables.net/colvis/1.1.1/js/dataTables.colVis.min.js"></script>

`

**Comment by peppo1616** [comment]
yes, i'm using nuget package and Those bundles

            bundles.Add(new ScriptBundle("~/bundles/datatableplugin").Include(
                "~/scripts/datatables/media/js/jquery.dataTables.min.js",
               "~/Content/jquery-datatables-column-filter/dataTables.tableTools.min.js",
               "~/Content/jquery-datatables-column-filter/jquery-ui-timepicker-addon.js",
               "~/Content/jquery-datatables-column-filter/media/js/jquery.dataTables.columnFilter.js",
               "~/Content/jquery-datatables-column-filter/dataTables.colVis.min.js",
               "~/scripts/datatables/plugins/bootstrap/dataTables.bootstrap.js"));


            bundles.Add(new StyleBundle("~/bundles/datatableplugincss").Include(
                "~/scripts/datatables/plugins/bootstrap/dataTables.bootstrap.css",
                "~/Content/jquery-datatables-column-filter/dataTables.tableTools.css",
                "~/Content/jquery-datatables-column-filter/jquery-ui-timepicker-addon.css",
                "~/Content/jquery-datatables-column-filter/media/js/jquery.dataTables.columnFilter.css",
                "~/Content/jquery-datatables-column-filter/dataTables.colVis.css",
                "~/Content/themes/Aristo/jquery-ui-1.8.7.custom.css"));


I can solve the problem specifiing order, or positioning all visible=False properties after visible's one in my ViewModel in this way, but it's very very silly and naturally a bad workaround

    [DataTables(DisplayName = "Titolo",Order = 1)]
    public virtual string Title { get; set; }

    [DataTables(DisplayName = "Tipologia",Order = 2)]
    public virtual string Type { get; set; }

    [DataTables(Visible = false,Searchable = false, Order = 7)]
    [DataTablesFilter(DataTablesFilterType.None)]
    public virtual string Url { get; set; }

    [DataTables(Visible = false, Searchable = false,Order = 8)]
    public virtual string CCE { get; set; }

    [DataTables(Visible = false, Searchable = false,Order = 9)]
    public virtual string Subject { get; set; }

    [DataTables(DisplayName = "Autore", ,Order = 3)]
    public virtual string Creator { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 10)]
    public virtual string Contributor { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 11)]
    public virtual string Description { get; set; }

    [DataTables(Visible = true, Order = 4)]
    public virtual string Publisher { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 12)]
    public virtual string Date { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 13)]
    public virtual string Format { get; set; }

    [DataTables(DisplayName = "Source", Order = 5)]
    public virtual string Source { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 14)]
    public virtual string Language { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 15)]
    public virtual string Relation { get; set; }

    [DataTables(Visible = false, Searchable = false, Order = 16)]
    public virtual string Coverage { get; set; }

    [DataTables(DisplayName = "Licenza", Order = 6)]
    public virtual string Rights { get; set; }

**Comment by mcintyre321** [comment]
I think you also need to set 'vm.ColVis = true'

**Comment by peppo1616** [comment]
done, but Column filtering not woking correctly. Try to filter on Author result filtering on Rights (that's not shown on columns why is set to Visible = false).

Can i provide something can help to find the problem? It's the problem clear? I'm talking about Column Filters..

**Comment by mcintyre321** [comment]
Can you post the source code of the rendered html page? I'd like to see how the plugins are being initialised.

**Comment by peppo1616** [comment]
don't know if usable... this is the code: 
https://justpaste.it/twrl

sorry for the time

**Comment by mcintyre321** [comment]
If you look at the html you posted you can find `"bUserColVis":false` in the javascript. This should be set to true (which ought to be set if you use `vm.ColVis = true`in the cshtml).

Can you post the cshtml for the page?

**Comment by peppo1616** [comment]
thanks, for your disponibility, my mistake, html shared was old version...

Set as you told and works great. 

This is the html code:

https://justpaste.it/tww4

and this cshtml

https://justpaste.it/twwa

Thank you for your great patience! Solved!

**Comment by mcintyre321** [comment]
No problem!
