### ISSUE TITLE
Error when pass decompiled query to DataTablesResult.Create

### ISSUE THREAD

**Issue by ftoyon** [mcintyre321/mvc.jquery.datatables#147]
Hi !

I'm using DelegateDecompiler.EntityFramework for complex query and auto mapping but the Mvc.JQuery.DataTables.DynamicLinq.DynamicQueryable.OrderBy method failed whith the error :

Unable to cast an object of type 'Delegate Decompiler.Decompile IQueryable' in kind 'System.Linq.IQueryable`1 [ListesValeursListViewModel]'.

`
            return DataTablesResult.Create(DbContext.ListesValeurs.Where(w => !w.ListeEtat).ProjectTo<ListesValeursListViewModel>().Decompile(),dataTableParam, uv => new { });`

Best regard's

**Comment by mcintyre321** [comment]
Hmm, thorny problem. I'm not too familiar with the inner workings of DelegateDecompiler, @hazzik might know the answer to this one. The QueryProvider returned by .Decompile() maybe should filter out the DelegateDecompiler extensions when a call to .Expression is made?

**Comment by mcintyre321** [comment]
@ftoyon did you manage to fix this one?
