### ISSUE TITLE
column filters stopped working when upgrading to v1.3.44 through NuGet

### ISSUE THREAD

**Issue by MrCsabaToth** [mcintyre321/mvc.jquery.datatables#149]
The `DataTablesParam` of my `getDataUrl` function does not have any `sSearchValues` filled in any more. I'm not sure if I'm doing something wring or it's a bug in the package. Definitely something happened along the upgrade. The generic search box causes crash.
Details: https://stackoverflow.com/questions/37802470/mvc-jquery-datatables-column-filters-stopped-working

**Comment by mcintyre321** [comment]
What 'crash' do you see? Is there anything in the Javascript console?

There was a change to DateTime types, but it should have made them work in the search box...

**Comment by MrCsabaToth** [comment]
So the crash is not with the column filters but the generic filter. I see the `sSearch` value filled in with the search term (as opposed to the column filters where the `sSearchValues` are not filled any more).

I create my result query set and pass it onto the `DataTablesResult.Create` along with the `dataTableParam`. The exception is `ArgumentOutOfRangeException`. Maybe even Mvc.JQuery.DataTables itself is surprised that there's nothing in `sSearchValues`?

I'm attaching the screenshot of the top of the callstack.
![mvc_jquery_datatables_search_crash](https://cloud.githubusercontent.com/assets/744949/16103923/8d33ce9c-3331-11e6-8d2d-f91fc51e4db5.jpg)

**Comment by MrCsabaToth** [comment]
To answer more questions:
jQuery 2.2.3
DataTables 1.10.11

I must do something wrong because the I see that your demo site is working fine. However my software was kinda working well.

**Comment by deman** [comment]
@MrCsabaToth I guess it is related to #148. Try upgrade to 1.3.45

**Comment by MrCsabaToth** [comment]
Solved it!

**Comment by MrCsabaToth** [comment]
So basically duplicate, or related

**Comment by mcintyre321** [comment]
1.3.47 definitely includes the ModelBinder now, sorry for an inconveniences!
