### ISSUE TITLE
Master-Detail example

### ISSUE THREAD

**Issue by deman** [mcintyre321/mvc.jquery.datatables#150]
Do you have any example for Master-Detail case in which I need to supply additional parameters besides dataParams?

I know it was briefly answered in #69 but it is not very clear how that can be achieved. Currently I resort to use TempData but that might not be a best practise.

**Comment by mcintyre321** [comment]
You just need to add a parameter alongside the DataTablesParam on the action that returns the data, and then filter the data source with a .Where clause.

Then you initialise the DataTableVm with the url, with that already prefilled.

```
public TableController
{

    IQueryable<ChildItems> data = ...;

    public GetChildren(int parentId){
           var getDataUrl = Url.Action(nameof(GetChildrenTableData), new { parentId });
           var vm = DataTablesHelper.DataTableVm<UserTableRowViewModel>("idForTableElement", getDataUrl);
           ... //configure vm
           return View("Parent", vm);
    }
    public DataTablesResult<ChildRowModel> GetChildrenTableData(DataTablesParam dataTableParam, int parentId)
    {
        IQueryable<ChildEntities> allChildItems = ...; //from your data source
        var childQueryable = allChildItems.Where(ri => ri.ParentId == parentId).Select(c => new ChildRowModel { ... });
        return DataTablesResult.Create(queryable, dataTableParam);
   }

}

```

**Comment by mcintyre321** [comment]
Does that do the trick?

**Comment by deman** [comment]
I have tried the following:

ViewModel:
```
public class InvoiceItemViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string ExtDescription { get; set; }
        public string TaxCode { get; set; }
        public string AmountxGST { get; set; }
        public string GST { get; set; }
        public string Total { get; set; }
    }
```
In view:

```
@{
    var getDataUrl = Url.Action(nameof(InvoicesController.GetInvoiceItems), new { InvoiceId = Model.Id });
    var vmInvoice = DataTablesHelper.DataTableVm<TravelInvoice.Models.DataTablesView.InvoiceViewModel>("table-invoiceitems-id", getDataUrl);
 
    vmInvoice.TableClass = "table table-hover table-responsive";
}
@Html.Partial("DataTable", vmInvoice)
```

In Controller
```
public DataTablesResult<InvoiceItemViewModel> GetInvoiceItems(DataTablesParam dataTableParam, int InvoiceId)
        {
```

Running the above, I got the following warning message prompt:
`DataTables warning: table id=table-invoiceitems-id - Requested unknown parameter '7' for row 0, column 7. For more information about this error, please see http://DataTables.net/tn/4`

I guess this warning message is due to by default datatables will show 'Loading data from table..' message which use colspan. 

I haven't figure out how to fix this yet.

**Comment by mcintyre321** [comment]
The first thing to try is making a normal action without the additional parameter e.g.

```
@{
    var getDataUrl = Url.Action(nameof(InvoicesController.GetInvoiceItems));
```

```
public DataTablesResult<InvoiceItemViewModel> GetInvoiceItems(DataTablesParam dataTableParam)
{
    int InvoiceId = 4;
```

And just see if the table works without the master id.

**Comment by deman** [comment]
Hmm it still giving same warning prompt when hard-coding the InvoiceId.

**Comment by mcintyre321** [comment]
- Is the ModelBinder registered? 
- Does the GetInvoiceItems method get called by AJAX?

**Comment by deman** [comment]
ModelBinder is registered and the method get called by AJAX.

I just upgraded to version 1.3.49 and the problem is gone. Any specific update you have done for this latest release?

**Comment by mcintyre321** [comment]
Depends which version you were on before! The auto-registration of the model binder was fixed recently.
