### ISSUE TITLE
Datetime parsed to localTime.

### ISSUE THREAD

**Issue by Sarogatip** [mcintyre321/mvc.jquery.datatables#153]
While passing DateTime object to DataTablesResult.Create method it is parsed to UTC time zone. In order to change it I had to include your whole project to my solution just to change:
```
static StringTransformers()
{
     RegisterFilter<DateTimeOffset>(dateTimeOffset => dateTimeOffset.ToLocalTime().ToString("g"));
     RegisterFilter<DateTime>(dateTime => dateTime.ToLocalTime().ToString("g"));
}
```

to:
```
static StringTransformers()
{
     RegisterFilter<DateTimeOffset>(dateTimeOffset => dateTimeOffset.ToString("g"));
     RegisterFilter<DateTime>(dateTime => dateTime.ToString("g"));
}
```

Is there any better way to do that? I'd like to display exactly this date which is stored in my database.
Thanks for any tips.

**Comment by mcintyre321** [comment]
Before I give you a detailed answer, let me check I understand:

You 
   a/ store UTC times in your database and
   b/ want to display them in UTC to the user (no matter what TZ they are currently in)?

**Comment by mcintyre321** [comment]
Also, are you using date range column filters?

If not you can just use a transform to render the underlying string type as you like: https://github.com/mcintyre321/mvc.jquery.datatables/wiki/How-to-manipulate-format-prettify-the-output-column-data-after-the-filters-have-been-applied

**Comment by mcintyre321** [comment]
Also I think `StringTransformers.RegisterFilter` is public, so you can overwrite the DateTime transformers from your global.asax.cs/Startup.cs without having to include the whole project as source.

**Comment by Sarogatip** [comment]
You understand me correctly.
Using date range column filter worked form me like a charm, but it forced me to change each controller where I use `DataTable.Create()`.
If you could post how to overwrite `StringTransformers.RegisterFilter` in global.asax.cs I would be really greatfull.

**Comment by mcintyre321** [comment]
I haven't had a chance to test this, but you should be able to do this:

````

protected void Application_Start(object sender, EventArgs e) {
{
     StringTransformers.RegisterFilter<DateTimeOffset>(dateTimeOffset => dateTimeOffset.ToString("g"));
     StringTransformers.RegisterFilter<DateTime>(dateTime => dateTime.ToString("g"));
}

```

**Comment by Sarogatip** [comment]
It works very well. Thank you very much.
