### ISSUE TITLE
vs2013 support

### ISSUE THREAD

**Issue by c-arnab** [mcintyre321/mvc.jquery.datatables#156]
It would be great to have a vs2013 solution as well..

**Comment by mcintyre321** [comment]
It's difficult to maintain two solutions, and VS2015 Community Edition is free*. Is there a reason you can't use it?


*ish

**Comment by c-arnab** [comment]
I would like to try to use this project in one of my current projects which is on vs 2013. 
So, I wanted to view at least the examples in vs 2013.. The example project is on dotnet 4.5
I loaded only the example project in vs 2013 and restored the nuget packages and added the nuget package 'Mvc.JQuery.DataTables', But after this when i build I get the following errors

1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(41,48,41,54): error CS0103: The name 'nameof' does not exist in the current context
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(41,55,41,60): error CS0120: An object reference is required for the non-static field, method, or property 'Mvc.JQuery.DataTables.Example.Controllers.FacetController.UserFacetRowViewModel.Email.get'
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(45,48,45,54): error CS0103: The name 'nameof' does not exist in the current context
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(45,55,45,62): error CS0120: An object reference is required for the non-static field, method, or property 'Mvc.JQuery.DataTables.Example.Controllers.FacetController.UserFacetRowViewModel.IsAdmin.get'
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(50,48,50,54): error CS0103: The name 'nameof' does not exist in the current context
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(50,55,50,63): error CS0120: An object reference is required for the non-static field, method, or property 'Mvc.JQuery.DataTables.Example.Controllers.FacetController.UserFacetRowViewModel.Position.get'
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(53,84,53,90): error CS0103: The name 'nameof' does not exist in the current context
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\FacetController.cs(53,91,53,96): error CS0120: An object reference is required for the non-static field, method, or property 'Mvc.JQuery.DataTables.Example.Controllers.FacetController.UserFacetRowViewModel.Hired.get'
1>D:\del\datatables-mvc\mvc.jquery.datatables-master\Mvc.JQuery.Datatables.Example\Controllers\HomeController.cs(16,41,16,47): error CS0103: The name 'nameof' does not exist in the current context

Any ideas what could be going wrong..

**Comment by c-arnab** [comment]
ok, figured out that nameof is part of c#6.0 and so will compile only on vs2015

**Comment by mcintyre321** [comment]
Yup, you'd be better off using VS2015. It can compile code to work against lower .net runtimes.
