### ISSUE TITLE
Remove /Content from solution

### ISSUE THREAD

**Issue by maximejobin** [mcintyre321/mvc.jquery.datatables#158]
I downloaded the project but I could not compile it.

The reason is that there is, in the solution but not on disk, a `/Content` folder in the `.Core` project .

Deleting it and rebuilding solved the issue.

**Comment by mcintyre321** [comment]
Ta, will remove next time I edit the project. Weirdly, the [AppVeyor build](https://ci.appveyor.com/project/mcintyre321/mvc-jquery-datatables) is happy with the current code.

Quick thought - did you do a recursive submodule checkout?

**Comment by maximejobin** [comment]
I was simply looking for examples on "how to use it" so I went on the project page and clicked on "Download ZIP" (top right).

**Comment by maximejobin** [comment]
I see in the `.csproj` that there is a link with an embedded resource. That said, it looks like the link could not be made correctly when I opened the solution.

**Comment by mcintyre321** [comment]
Ah, I wonder if that's the reason - github download doesn't download the content from the submodules...

**Comment by mcintyre321** [comment]
Project needs to be cloned not downloaded.
