### ISSUE TITLE
Error after Upgrading to 1.3.51

### ISSUE THREAD

**Issue by FranzKiermaier** [mcintyre321/mvc.jquery.datatables#159]
Hi,
After upgrading to Version 1.3.51 I get an exception in the line 

`var result = DataTablesResult.Create(taskList.AsQueryable(), dataTableParam, Mvc.JQuery.DataTables.Models.ArrayOutputType.ArrayOfObjects);`

The exception says: "The sequence contains several matching elements.". 

It used to work until Version 1.3.37. From 1.3.38 it doesn't work anymore. Do I have to change my code? I couldn't figure out what to change to get objects in my Json Result.

**Comment by mcintyre321** [comment]
Do you have the stacktrace and posted dataTableParam?

**Comment by FranzKiermaier** [comment]
Hi, 

this is the Exception and StackTrace:

```
System.InvalidOperationException: Die Sequenz enthält mehrere übereinstimmende Elemente.
   bei System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Mvc.JQuery.DataTables.DataTablesResult.Create(IQueryable queryable, DataTablesParam dataTableParam, Object transform, ResponseOptions responseOptions)
   bei SPAppSuite.Web.Controllers.ResourcePlanningController.<GetMyTasksTable>d__1.MoveNext() in D:\Projekte\SPAppSuite\SPAppSuite.Web\Controllers\ResourcePlanningController.cs:Zeile 72.
```

And this is the dataTableParam object as Json:

`{"iDisplayStart":0,"iDisplayLength":50,"iColumns":4,"sSearch":"","bEscapeRegex":false,"iSortingCols":1,"sEcho":1,"sColumnNames":["Title","DueDate","Status","Effort"],"bSortable":[true,true,true,true],"bSearchable":[true,true,true,true],"sSearchValues":["","","",""],"iSortCol":[0],"sSortDir":["asc"],"bEscapeRegexColumns":[false,false,false,false]}`

Thanks for your help :-)

**Comment by mcintyre321** [comment]
I think it's a bug in [this `DataTablesResult.Create`](https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables/DataTablesResult.cs#L72) method.

Can you try one of the overloads with a generic argument? i.e. use `taskList.AsQueryable().Cast<Task>()` instead of `taskList.AsQueryable()`?

**Comment by mcintyre321** [comment]
Closing for now.
