### ISSUE TITLE
Upgraded last version

### ISSUE THREAD

**Issue by daidaglez** [mcintyre321/mvc.jquery.datatables#161]
I´ve upgraded to last version and now i received this bug "DataTables warning (table id=""): Requested unkind parameter '' from the data source for row 0"
I also have bugs to load another scripts 
Same code worked before upgraded
My code:
t
![captura de pantalla 2017-05-10 a las 12 08 44](https://cloud.githubusercontent.com/assets/28594514/25894573/9b673b68-357c-11e7-8d86-9453b379c45b.png)
able = $table.dataTable(
Plugins.DataTablesPlugin.getOptions("usuarios",
{
aaSorting: [[5, "asc"]],
aoColumns: [
{
mData: "details",
bSortable: false,
mRender(data, type, row) {
return <a title='${resources["Title_ShowUserDetails"] }' href='${$("#urlUsers").val()}?userId=${row.Id }''><img src='../Content/images/drivingschools/item-alumnos.png\'/></a>;
}
},

Thanks

**Comment by mcintyre321** [comment]
Are there any javascript files which have failed to load (check the network tab)?

**Comment by daidaglez** [comment]
Code worked before upgraded, i attached network screen with scripts that failed after upgrading

**Comment by mcintyre321** [comment]
You've uploaded the console logs but not the network screen...

Can you compare your scripts against https://aspdatatables.azurewebsites.net/?
