### ISSUE TITLE
RegisterDataTablesModelBinder file not being added by NuGet

### ISSUE THREAD

**Issue by jandic** [mcintyre321/mvc.jquery.datatables#167]
Hi,

when I add NuGet package Mvc.Jquery.Datatables, it used to add RegisterDataTablesModelBinder.cs file automatically (version 1.3.x). However, after upgrading to the latest version (1.5.36), that file is no longer being added.

I am using .net 4.5.1 version.

Thanks,
Pavel

**Comment by mcintyre321** [comment]
I think that it is no longer be possible to register a file in the project with the new .NET tooling. I should probably update the documentation (or a helpful user could!)
