### ISSUE TITLE
Mvc.JQuery.DataTables Version 1.5.36 got error when search with filter input

### ISSUE THREAD

**Issue by zabahey** [mcintyre321/mvc.jquery.datatables#168]
I download your package version 1.5.36 from NuGet then follow instructions from [http://aspdatatables.azurewebsites.net/](http://aspdatatables.azurewebsites.net/).
Everything looks good until I try to search from filter input

"System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'".
My target framework point to 4.6.1 and MVC version 5.2.3.0

**Comment by mcintyre321** [comment]
Which MVC version are you using? (5 or core)

Does the example project run on your computer?

What is the full stack trace?

**Comment by rauntska** [comment]
I got the same issue. Cloning the repo and running the example fails. Most of the projects load failed or are unavailable
When trying to reload project i get :
![image](https://user-images.githubusercontent.com/16056798/34120807-8a7c273e-e42f-11e7-9db7-56b7d2cadf65.png)

Running MVC5 VS 2015 Professinal

**Comment by rauntska** [comment]
ok i tried in VS2017. The example project seems to run there. + all projects are loaded. 
So it seems to be a VS2015 issue? Hope that this is related to the initial problem

**Comment by mcintyre321** [comment]
Can you check if the DataTables Model Binder is registered? It used to work off a template which self-installed but I think that's been removed from Nuget's capabilities.

**Comment by mcintyre321** [comment]
The project needs the latest VS2017 BTW

**Comment by rauntska** [comment]
Sry for the late reply. Managed to install VS2017  . Tried to run my project where the libraries are installed through Nuget. Version 1.5.36

But still got the same issue :(

@mcintyre321  How do i view if the model binder is registered?

**Comment by rauntska** [comment]
Found it, after updating the nugets to the latest version i also had to add a new class- that solved the issue

```
using System.Web;
using System.Web.Mvc;
using Mvc.JQuery.DataTables;
using MyNameSpace;

[assembly: PreApplicationStartMethod(typeof(RegisterDataTablesModelBinder), "Start")]

namespace MyNameSpace
{

    public static class RegisterDataTablesModelBinder
    {
        public static void Start()
        {
            if (!ModelBinders.Binders.ContainsKey(typeof(DataTablesParam)))
                ModelBinders.Binders.Add(typeof(DataTablesParam), new DataTablesModelBinder());
        }
    }
}
```

**Comment by mcintyre321** [comment]
Nice one, hope it works out for you. I'll update the docs when I get a chance.
