### ISSUE TITLE
Export disable property

### ISSUE THREAD

**Issue by rauntska** [mcintyre321/mvc.jquery.datatables#171]
Hello,
Thanks for the great work done with this!

I've got a question though. Im using the CSV,Excel,PDF export buttons. I have a hidden column which i must have, but i dont want to export. Is there some property attribute which skips the export for a particular property ?

```
  [DataTables(Visible = false)]
  public VACATIONS Vacation { get; set; }
```

Thanks!

**Comment by mcintyre321** [comment]
I'm not sure... You'll have to look up the docs for datatables and the
visibility and for export plugins.

If you find how to do it in JavaScript we can extend the library to use
those settings.

**Comment by rauntska** [comment]
Found it   [DataTablesExclude] does the trick.
```
        [DataTablesExclude]
        [DataTables(Visible = false)]
        public VACATIONS Vacation { get; set; }
```

**Comment by mcintyre321** [comment]
It's been a while since I've used the library! Glad to see you're getting
on with it. Are you using it with mvc5 or core?
