### ISSUE TITLE
Compatibility with v1.10.19

### ISSUE THREAD

**Issue by cameronws** [mcintyre321/mvc.jquery.datatables#172]
Is this project or any fork compatible with v1.10.19 of DataTables.Net?

**Comment by mcintyre321** [comment]
Haven't tested it I'm afraid. Happy to accept a PR updating it though!

**Comment by cameronws** [comment]
Ok thanks. The current version of this project is working fine for me right now. I don't have time at the moment to do a PR to get it to work with the current version of DataTables.Net - I assume an update on the jquery column filter plugin would also need to be updated.
