### ISSUE TITLE
Update NuGet packages

### ISSUE THREAD

**Issue by jandic** [mcintyre321/mvc.jquery.datatables#176]
Hi, would you mind updating NuGet packages? They seem to be out of sync with the current version of the repository. I also submitted a bug fix as a pull request and it would be great if that could be included.

Thank you very much!

Pavel

**Comment by jandic** [comment]
Hi, can you please publish updated NuGet packages? I would like to use the fix I submitted last week in a project and do not want to create an "unofficial" NuGet package. Thanks.

**Comment by mcintyre321** [comment]
That should be done, thanks for nagging me. My CI systems Nuget key had expired...

**Comment by jandic** [comment]
Great, thanks a lot!
