### ISSUE TITLE
Case-insensitive search

### ISSUE THREAD

**Issue by hermankan** [mcintyre321/mvc.jquery.datatables#44]
Unlike client-side search, the one on server is always case-sensitive. The StringFilter defines it as follows:

"({0} != null && {0} != \"\" && ({0} ==  {1} || {0}.StartsWith({1}) || {0}.Contains({1})))"

Could you add in an optional parameter that would make the search case-insensitive.
Thanks.

**Comment by MrCsabaToth** [comment]
Could DataTables native case insensitive option
https://datatables.net/reference/option/search.caseInsensitive
provide an alternative (sometimes better) solution? Certainly less code.

**Comment by MrCsabaToth** [comment]
The 3 step guide should be accessible as a part of the documentation, because I think it's much more common to provide case insensitive search than the other way.

**Comment by MrCsabaToth** [comment]
Just for anyone who follows the 1-2-3 step-by-step guide of  @mcintyre321, you need to explicitly `using QueryInterceptor` (what you installed from NuGet package), the IntelliSense didn't help for me. Otherwise you'll get a compilation error about the `InterceptWith` call.

**Comment by mcintyre321** [comment]
@MrCsabaToth The caseInsensitive setting isn't currently mapped into case insensitive statements in the expression that is built up, but this would probably be the most 'correct' way to fix this issue.

It might cause some issues with Linq providers though, depending on how they handle case insensitity in Expressions (some expressions will use x.ToUpper() == param.ToUpper(), others StringComparer etc).

I've added the guide to the wiki at https://github.com/mcintyre321/mvc.jquery.datatables/wiki/Changing-case-sensitivity. If there are other areas you have found tough to work with, any contributions to the wiki would be most welcome!
