### ISSUE TITLE
Custom search field

### ISSUE THREAD

**Issue by AndiRudi** [mcintyre321/mvc.jquery.datatables#91]
Hi, want to add the search field by myself. I added the a new input field and the appropriate javascript to trigger the filter function like this and in general it works:

 $(function () {
        oTable = $('#maintable').dataTable();
        $('#search').keyup(function () {
            oTable.fnFilter($(this).val());
        })
    });

But when I disable the builtin search field with the command vm.ShowSearch = false; then the search does not work anymore. Maybe the serverside wrapper disables search then?

**Comment by mcintyre321** [comment]
Closing due to lack of PR
